theme = "rose_pine"

[editor]
line-number = "relative"
mouse = true
text-width = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
