[language-server.rust-analyzer.config]
inlayHints.closingBraceHints.minLines = 1

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "latex"
formatter = { command = "latexindent", args = ["-w", "%f"] }
